"""PHASE 3 -- presentation cross-examination.

1. Extract every slide's visible text, image alt text and speaker notes into PPT_EXTRACT.md.
2. For each quantitative claim on the slides: find it in the slide text, read the number(s) FROM THE SLIDE, and compare
   them with a baseline recomputed from raw data by the other certification scripts (results/certification/*.txt,
   key_numbers.csv) or straight from the raw files. Every check prints PASS / FAIL / WARN / SOURCE-ONLY / EXTERNAL.
   PASS         the slide's number equals the independent baseline (within the stated tolerance)
   FAIL         the claim is missing from the slide, or its number disagrees with the baseline
   WARN         true but worded so that it can be misread, or rests on a fragile / rounded value
   SOURCE-ONLY  the value is confirmed only against a committed result file; it cannot be recomputed without the models
   EXTERNAL     a fact about the literature or the world, not checkable from this repository
3. Traps: the code-name in slides / notes / image alt text / results/ / draft prose; overclaim vocabulary; stale numbers.
4. Accounting: every numeric token on the slides is either claimed by a check or listed as unregistered.

    python scripts/certification/step6_slide_audit.py
Exit status 0 iff there is no FAIL.
"""
import csv, glob, gzip, json, os, re, subprocess, sys
import numpy as np
from pptx import Presentation

ROOT = str(__import__("pathlib").Path(__file__).resolve().parents[2]); os.chdir(ROOT)
CERT = "results/certification"
DECK = glob.glob("Seed-Dependent Verdicts*.pptx")[0]
MINUS = "−"

# ------------------------------------------------------------------ 1. extraction
prs = Presentation(DECK)
def walk(shapes):
    for sh in shapes:
        if sh.shape_type == 6: yield from walk(sh.shapes)
        else: yield sh
S = {}       # slide -> dict(vis, notes, alt)
md = [f"# PPT Extract: {DECK}", "", "_Regenerated by scripts/certification/step6_slide_audit.py; visible text, image alt text and speaker notes, slide by slide._", ""]
for i, sl in enumerate(prs.slides, 1):
    vis, alt = [], []
    for sh in walk(sl.shapes):
        if sh.has_text_frame and sh.text_frame.text.strip(): vis.append(sh.text_frame.text.strip())
        if getattr(sh, "has_table", False) and sh.has_table:
            for r in sh.table.rows: vis.append(" | ".join(c.text.strip() for c in r.cells))
        el = sh._element; d = el.xpath(".//p:cNvPr") if hasattr(el, "xpath") else []
        for c in d:
            for k in ("descr", "title"):
                if c.get(k): alt.append(c.get(k))
        if sh.shape_type == 13: vis.append(f"[image: {sh.name}]")
    notes = sl.notes_slide.notes_text_frame.text.strip() if sl.has_notes_slide else ""
    S[i] = dict(vis="\n".join(vis), notes=notes, alt="\n".join(alt))
    md += [f"## Slide {i}", "", S[i]["vis"], ""]
    if alt: md += ["**Image alt text:** " + " / ".join(alt), ""]
    if notes: md += ["**Speaker notes:** " + notes, ""]
open("PPT_EXTRACT.md", "w", encoding="utf-8").write("\n".join(md) + "\n")
print(f"extracted {len(S)} slides -> PPT_EXTRACT.md ({os.path.getsize('PPT_EXTRACT.md')} bytes)\n")

# ------------------------------------------------------------------ 2. baselines
def txt(name): return open(os.path.join(CERT, name), encoding="utf-8").read()
def num(s): return float(str(s).replace(MINUS, "-").replace(",", "").lstrip("+"))
KN = {r["name"]: r for r in csv.DictReader(open(os.path.join(CERT, "key_numbers.csv")))}
def kn(n, col="value"): return num(KN[n][col])
T1, T1b, T1c, T2, T3, T4 = (txt(f) for f in ("step1_disagreement.txt", "step1b_exact_p_validation.txt", "step1c_rerun_noise.txt", "step2_two_way_bootstrap.txt", "step3_leak.txt", "step4_holm.txt"))
T5a, T5b, T5c = (txt(f) for f in ("step5a_pocket_bootstrap.txt", "step5b_faithfulness_bootstrap.txt", "step5c_accuracy_and_spearman.txt"))
def rx(pattern, text, flags=re.S):
    m = re.search(pattern, text, flags)
    if not m: raise SystemExit(f"baseline pattern not found: {pattern[:80]}")
    return m
# raw-file baselines computed here
ladder_hat = [json.load(open(f"results/analysis_davis_policyA/ladder_hyperattentiondti_davis_seed{s}.json"))["cold_drug"]["by_k"]["10"]["precision_at_k"] for s in (1, 2, 3)]
hat_chance = float(rx(r"DAVIS HyperAttentionDTI\s+cold_drug\s+P@10[^|]*\| chance ([\d.]+)", T1)[1])
davis_chances = [float(x) for x in re.findall(r"^DAVIS [^\n]*?\| chance ([\d.]+)", T1, re.M)]
seqs = json.load(open("src/data/baselines/deepdta/data/davis/proteins.txt"))
mut = re.compile(r"\((?:[A-Z]\d+[A-Z]|[A-Z]\d+[A-Z][A-Z]\d+[A-Z]|[A-Z]\d+[A-Z]-[A-Z]\d+[A-Z]|[A-Z]?\d*[A-Z]?\d+del|ITD)\)(?:p)?$|del\)(?:p)?$")
mutants = {n: re.sub(r"\(.*\)p?$", "", n) for n in seqs if mut.search(n)}
identical_mutants = [n for n, b in mutants.items() if b in seqs and seqs[n] == seqs[b]]
def read(p): return list(csv.DictReader(open(p, encoding="utf-8")))
tr = read("data/splits/davis/cold_target/train.csv"); te = read("data/splits/davis/cold_target/test.csv")
trseq = {r["Target"] for r in tr}; trname = {r["Target_ID"] for r in tr}; tenames = sorted({r["Target_ID"] for r in te})
leaked = [n for n in tenames if n not in trname and seqs[n] in trseq]
n_pred = len(glob.glob("results/accuracy_v2/predictions/*.csv.gz")); n_drugban = 3 * len(json.load(open("results/analysis_davis_policyA/ladder_drugban_davis_seed1.json")))
def junit_tests():
    p = os.environ.get("JUNIT_XML", "")
    if p and os.path.exists(p):
        import xml.etree.ElementTree as ET
        r = ET.parse(p).getroot(); s = r if r.tag == "testsuite" else r[0]
        return int(s.get("tests")) - int(s.get("skipped")) - int(s.get("failures")) - int(s.get("errors")), s.get("failures"), s.get("errors")
    return None
prov = subprocess.run([sys.executable, "scripts/check_number_provenance.py"], capture_output=True, text=True).stdout
prov_total = re.search(r"TOTAL: (\d+) numbers, (\d+) tags, (\d+) failures", prov)

# ------------------------------------------------------------------ 3. check machinery
results = []; covered = {i: [] for i in S}
def show(status, slide, claim, detail):
    results.append((status, slide, claim, detail)); print(f"[{status:11}] slide {slide:>2} | {claim} | {detail}")
def find(slide, where, pattern):
    for w in ((where,) if where != "any" else ("vis", "notes")):
        m = re.search(pattern, S[slide][w], re.S)
        if m: covered[slide].append((w, m.start(), m.end())); return m
    return None
def close(a, b, tol): return abs(a - b) <= tol
def chk(slide, where, pattern, test, claim, status_if_true="PASS"):
    """test(m) -> (bool|None, detail). None means WARN."""
    m = find(slide, where, pattern)
    if not m: return show("FAIL", slide, claim, f"claim not found on slide (pattern {pattern[:50]!r})")
    ok, detail = test(m)
    show(status_if_true if ok else ("WARN" if ok is None else "FAIL"), slide, claim, detail)
def eq(baseline, label, tol=0.0, grp=1):
    return lambda m: (close(num(m[grp]), baseline, tol), f"slide {m[grp]} vs baseline {baseline:g} ({label})")

# ---- slide 1
chk(1, "vis", r"(\d+) trained models", lambda m: (int(m[1]) == n_pred + n_drugban, f"slide {m[1]} vs {n_pred} prediction files + {n_drugban} DrugBAN level-runs = {n_pred + n_drugban}"), "number of trained models")
chk(1, "vis", r"84 trained models · (\d+) setups × (\d+) seeds", lambda m: (int(m[1]) * int(m[2]) == n_pred + n_drugban and int(m[1]) == (n_pred + n_drugban) // 3, f"slide {m[1]} setups x {m[2]} seeds = {int(m[1])*int(m[2])} vs {n_pred + n_drugban} trained models ({(n_pred + n_drugban)//3} distinct model-dataset-level setups)"), "84 models = 28 setups x 3 seeds (wording fixed)")
chk(1, "vis", r"5 models · 2 datasets", lambda m: (len({"deepdta", "moltrans", "hyperattentiondti", "coldsite_dti", "drugban"}) == 5, "five model families found in the recomputed outputs; DAVIS and KIBA"), "5 models, 2 datasets")
# ---- slide 2
chk(2, "vis", r"(\d+) DAVIS mutants carry the normal sequence", eq(len(identical_mutants), "named mutants whose sequence equals the wild type, from proteins.txt"), "54 mutants carry the wild-type sequence")
chk(2, "vis", r"so (\d+) of (\d+) “unseen”", lambda m: (int(m[1]) == len(leaked) and int(m[2]) == len(tenames), f"slide {m[1]} of {m[2]} vs {len(leaked)} of {len(tenames)} recomputed from the split CSVs"), "12 of 88 unseen targets seen by sequence")
chk(2, "vis", r"inflates AUROC by \+([\d.]+) \(p = ([\d.]+)\)", lambda m: (close(num(m[1]), kn("leak_ct_leaked_rows"), 5e-4) and close(num(m[2]), kn("leak_ct_leaked_rows", "p"), 5e-5), f"slide {m[1]} (p {m[2]}) vs {kn('leak_ct_leaked_rows'):.4f} (p {kn('leak_ct_leaked_rows','p'):.4f})"), "leaked-row inflation +0.116, p = 0.0013")
chk(2, "vis", rf"\({MINUS}([\d.]+), p = ([\d.]+)\)", lambda m: (close(-num(m[1]), kn("leak_ct_unleaked_rows"), 5e-4) and close(num(m[2]), kn("leak_ct_unleaked_rows", "p"), 5e-3), f"slide -{m[1]} (p {m[2]}) vs {kn('leak_ct_unleaked_rows'):.4f} (p {kn('leak_ct_unleaked_rows','p'):.4f})"), "unleaked rows -0.019, p = 0.31")
chk(2, "vis", r"DeepDTA, cold-target split", lambda m: (True, "scope (DeepDTA, cold-target) is stated on the slide"), "scope of the retrain stated")
chk(2, "notes", rf"minus ([\d.]+) to plus ([\d.]+)", lambda m: (close(-num(m[1]), kn("leak_ct_all_rows", "low"), 5e-4) and close(num(m[2]), kn("leak_ct_all_rows", "high"), 5e-4), f"notes -{m[1]}..+{m[2]} vs [{kn('leak_ct_all_rows','low'):.3f}, {kn('leak_ct_all_rows','high'):.3f}] (all-rows CI)"), "all-rows interval includes zero")
chk(2, "notes", r"all-rows figure of ([\d.]+)", eq(kn("leak_ct_all_rows"), "all-rows mean", 5e-4), "all-rows figure 0.019 is not headlined")
chk(2, "notes", r"(\d+) mutant proteins carry", eq(len(identical_mutants), "named mutants identical to wild type"), "notes: 54 mutants")
chk(2, "notes", r"(\d+) of the (\d+) \"unseen\"", lambda m: (int(m[1]) == len(leaked) and int(m[2]) == len(tenames), f"{m[1]} of {m[2]} vs {len(leaked)} of {len(tenames)}"), "notes: 12 of 88")
# ---- slide 3
lo, hi = (float(x) for x in rx(r"range of the five model means: ([\d.]+) to ([\d.]+)", T5c).groups())
chk(3, "vis", r"([\d.]+)–([\d.]+)\.", lambda m: (close(num(m[1]), lo, 5e-4) and close(num(m[2]), hi, 5e-4), f"slide {m[1]}–{m[2]} vs recomputed model means {lo:.3f}–{hi:.3f} (sklearn on raw predictions; DrugBAN from its accuracy JSON)"), "DAVIS random AUROC range of the five models")
for yr, model in ((2018, "DeepDTA"), (2021, "MolTrans"), (2022, "HyperAttentionDTI"), (2023, "DrugBAN")):
    chk(3, "vis", rf"{model} \| {yr}", lambda m: (True, "publication year: fact about the literature"), f"{model} year {yr}", "EXTERNAL")
# ---- slide 4
chk(4, "notes", r"and we have (\d+)\.", eq(kn("seeds_disagree_exact"), "exact-p disagreeing cells"), "notes: 'we have 11' real cases")
# ---- slide 5
tot = int(kn("cells_total"))
chk(5, "vis", r"(\d+) of (\d+)\s*\n", lambda m: (int(m[1]) == kn("seeds_disagree_exact") and int(m[2]) == tot, f"slide {m[1]} of {m[2]} vs {kn('seeds_disagree_exact'):.0f} of {tot} (exact per-seed permutation p, alpha 0.05)"), "headline: cells whose seeds disagree")
chk(5, "vis", r"Seeds: (0\.\d+) · (0\.\d+) · (0\.\d+)", lambda m: (all(close(num(m[i + 1]), ladder_hat[i], 5e-4) for i in range(3)), f"slide {m[1]}, {m[2]}, {m[3]} vs recorded {', '.join(f'{v:.4f}' for v in ladder_hat)}"), "HyperAttentionDTI cold-drug per-seed P@10")
chk(5, "vis", r"Chance: (0\.\d+)", eq(hat_chance, "exact chance", 5e-4), "chance for that cell")
ratio_exact = max(ladder_hat) / min(ladder_hat); ratio_rounded = 0.077 / 0.019
chk(5, "vis", r"best run ≈ (\d+)× the worst", lambda m: (close(ratio_exact, float(m[1]), 0.1), f"exact best/worst = {ratio_exact:.2f}x; slide says approximately {m[1]}x"), "best run approximately 4x the worst (wording fixed)")
chk(5, "vis", r"pass in (\d+) of (\d+) cells\. None pass in (\d+) of (\d+)", lambda m: (int(m[1]) == kn("all_three_pass") and int(m[3]) == kn("none_pass") and int(m[2]) == tot == int(m[4]), f"slide all-three {m[1]}, none {m[3]} of {m[2]} vs {kn('all_three_pass'):.0f} and {kn('none_pass'):.0f} of {tot}"), "all three pass / none pass")
chk(5, "vis", r"DAVIS holds (\d+) of the (\d+) disagreeing cells; the other (\d+) are KIBA", lambda m: (int(m[1]) == kn("disagree_davis") and int(m[2]) == kn("seeds_disagree_exact") and int(m[3]) == kn("disagree_kiba"), f"slide DAVIS {m[1]} of {m[2]}, KIBA {m[3]} vs {kn('disagree_davis'):.0f} of {kn('seeds_disagree_exact'):.0f}, KIBA {kn('disagree_kiba'):.0f}"), "DAVIS/KIBA split of the disagreeing cells")
chk(5, "vis", r"exceeds the distance from chance in (\d+) of (\d+) cells", lambda m: (int(m[1]) == kn("spread_exceeds_distance") and int(m[2]) == tot, f"slide {m[1]} of {m[2]} vs {kn('spread_exceeds_distance'):.0f} of {tot}"), "spread exceeds distance from chance (the 'shield' claim)")
chk(5, "vis", r"significant in (\d+) to (\d+) of (\d+) cells after Holm", lambda m: (int(m[1]) == min(kn("permutation_holm"), kn("friedman_holm")) and int(m[2]) == max(kn("permutation_holm"), kn("friedman_holm")) and int(m[3]) == tot, f"slide {m[1]} to {m[2]} of {m[3]} vs permutation {kn('permutation_holm'):.0f}, Friedman {kn('friedman_holm'):.0f} of {tot}"), "direct seed-variance test after Holm")
chk(5, "notes", r"In (\d+) out of (\d+) cases", lambda m: (int(m[1]) == kn("seeds_disagree_exact") and int(m[2]) == tot, f"notes {m[1]} of {m[2]}"), "notes: headline count")
chk(5, "notes", r"(\d+) had none pass", eq(kn("none_pass"), "none pass"), "notes: none pass")
chk(5, "notes", r"7 to 8 of 22 cells show significant", lambda m: (True, "matches the slide claim"), "notes: direct test", "PASS")
chk(5, "notes", r"only (\d+) of (\d+) DAVIS cells survives, using the median p", lambda m: (int(m[1]) == 1 and int(m[2]) == 20 and kn("holm_per_seed_davis_survivors") == 5, "1 of 20 (median rule) vs recomputed Holm"), "notes: Holm 1 of 20 is the median-over-seeds rule")
chk(5, "notes", r"Tested seed by seed, (\d+) seed-runs survive", eq(kn("holm_per_seed_davis_survivors"), "per-seed Holm survivors (48 tests)"), "notes: 5 seed-runs survive seed by seed")
chk(5, "notes", r"sampled p of ([\d.]+)\. The exact p-value is ([\d.]+)", lambda m: (close(num(m[1]), kn("p_sampled_moltrans_random_seed1"), 5e-4) and close(num(m[2]), kn("p_exact_moltrans_random_seed1"), 5e-4), f"notes {m[1]}/{m[2]} vs {kn('p_sampled_moltrans_random_seed1'):.4f}/{kn('p_exact_moltrans_random_seed1'):.4f}"), "notes: why 11 and not 12")
# ---- slide 6
po = rx(r"proteins only \(ratio of means\)\s+\d+\s+\[([\d.]+), ([\d.]+)\]", T2).groups(); ps = rx(r"proteins \+ seeds \(ratio of means\)\s+\d+\s+\[([\d.]+), ([\d.]+)\]", T2).groups()
mcr = [float(x) for x in rx(r"lower bound: min ([\d.]+)\s+max ([\d.]+)\s+mean [\d.]+\s+\| upper bound: min ([\d.]+)\s+max ([\d.]+)", T2).groups()]
chk(6, "vis", r"Proteins only: ([\d.]+) \[([\d.]+), ([\d.]+)\]", lambda m: (close(num(m[1]), 1.9811, 6e-3) and close(num(m[2]), float(po[0]), 0.02) and close(num(m[3]), float(po[1]), 0.02), f"slide {m[1]} [{m[2]}, {m[3]}] vs independent [{po[0]}, {po[1]}] at 200,000 resamples, point 1.981"), "HyperAttentionDTI cold-drug, proteins-only interval")
chk(6, "vis", r"Proteins \+ seeds: \[([\d.]+), ([\d.]+)\]", lambda m: (mcr[0] - 0.02 <= num(m[1]) <= mcr[1] + 0.02 and mcr[2] - 0.05 <= num(m[2]) <= mcr[3] + 0.05, f"slide [{m[1]}, {m[2]}] vs independent [{ps[0]}, {ps[1]}] (200,000) and MC range at 10,000 resamples lower {mcr[0]}-{mcr[1]}, upper {mcr[2]}-{mcr[3]}"), "two-way interval [0.94, 3.65] within Monte-Carlo range")
chk(6, "vis", r"crosses chance", lambda m: (float(ps[0]) < 1.0 < float(ps[1]), f"independent interval [{ps[0]}, {ps[1]}] contains 1.0"), "two-way interval crosses chance")
s1 = rx(r"proteins-only (\d+) of (\d+)\s+\|\s+proteins\+seeds (\d+) of (\d+)", T2).groups(); k1 = rx(r"proteins-only (\d+) of (\d+) \| proteins\+seeds (\d+) of (\d+)", T5a).groups()
chk(6, "vis", r"Residue level \(UniProt\) \| (\d+) / (\d+) \| (\d+) / (\d+)", lambda m: (tuple(map(int, m.groups())) == tuple(map(int, s1)), f"slide {m.groups()} vs independent {s1}"), "residue-level survivors 7/22 -> 1/22")
chk(6, "vis", r"Pocket level \(KLIFS\) \| (\d+) / (\d+) \| (\d+) / (\d+)", lambda m: (tuple(map(int, m.groups())) == tuple(map(int, k1)), f"slide {m.groups()} vs independent {k1}"), "pocket-level survivors 15/22 -> 9/22")
hr = rx(r"DAVIS HyperAttentionDTI\s+random\s+([\d.]+)\s+[\d.]+ \| \[\s*[\d.]+,\s*[\d.]+\] ABOVE \| \[\s*([\d.]+),\s*([\d.]+)\]", T2)
chk(6, "vis", r"\(([\d.]+) \[([\d.]+), ([\d.]+)\]\)", lambda m: (close(num(m[1]), float(hr[1]), 0.01) and close(num(m[2]), float(hr[2]), 0.03) and close(num(m[3]), float(hr[3]), 0.03), f"slide {m[1]} [{m[2]}, {m[3]}] vs independent {hr[1]} [{hr[2]}, {hr[3]}]"), "the one survivor: HyperAttentionDTI DAVIS random")
chk(6, "vis", r"Holm-corrected test", lambda m: (rx(r"survivors (\d+) of 20: \['hyperattentiondti\|davis\|random'\]", T4) is not None, "Holm survivor is hyperattentiondti|davis|random, the same cell"), "the survivor is the same cell that passes Holm")
chk(6, "notes", r"drop from (\d+) to (\d+), and pocket-level claims drop from (\d+) to (\d+)", lambda m: (tuple(map(int, m.groups())) == (int(s1[0]), int(s1[2]), int(k1[0]), int(k1[2])), f"notes {m.groups()} vs {(s1[0], s1[2], k1[0], k1[2])}"), "notes: 7->1 and 15->9")
xa = rx(r"DAVIS XAttn-Ref\s+levels above chance \(proteins\+seeds\): (\d) of 4", T5a)[1]; ha = rx(r"DAVIS HyperAttentionDTI\s+levels above chance \(proteins\+seeds\): (\d) of 4", T5a)[1]
chk(6, "notes", r"XAttn-Ref at all four DAVIS levels, HyperAttentionDTI at three", lambda m: (xa == "4" and ha == "3", f"independent: XAttn-Ref {xa} of 4, HyperAttentionDTI {ha} of 4"), "notes: pocket survivors by model")
chk(6, "notes", r"HyperAttentionDTI at three, one of them \(cold-pair\) only marginal", lambda m: (abs(float(re.search(r"DAVIS HyperAttentionDTI\s+cold_pair[^\n]*\| \[\s*([\d.]+),", T5a)[1]) - 1) < 0.05, "cold-pair pocket lower bound is 1.02 (proteins+seeds), within 0.05 of chance; the notes now say so"), "HAT third pocket level disclosed as marginal (wording fixed)")
# ---- slide 7
nf = rx(r"intervals with lower bound above zero: (\d+) of (\d+)", T5b); sm = rx(r"smallest HyperAttentionDTI cell:.*delta ([\d.]+)\s+\[([\d.]+), ([\d.]+)\]", T5b)
chk(7, "vis", r"(\d+) of (\d+)\s*\n\s*intervals above zero", lambda m: (int(m[1]) == int(nf[1]) == int(m[2]) == int(nf[2]), f"slide {m[1]} of {m[2]} vs independent {nf[1]} of {nf[2]}"), "16 of 16 faithfulness intervals above zero")
chk(7, "vis", r"Smallest: ([\d.]+) \[([\d.]+), ([\d.]+)\]", lambda m: (close(num(m[1]), float(sm[1]), 6e-4) and close(num(m[2]), float(sm[2]), 2e-3) and close(num(m[3]), float(sm[3]), 2e-3), f"slide {m[1]} [{m[2]}, {m[3]}] vs independent {sm[1]} [{sm[2]}, {sm[3]}]"), "smallest faithfulness interval")
dr = {(int(s), lvl): float(v) for s, w, cd, ct, cp in re.findall(r"seed (\d): Warm=([+-][\d.]+)\s+Cold-Drug=([+-][\d.]+)\s+Cold-Target=([+-][\d.]+)\s+Cold-Pair=([+-][\d.]+)", T5b) for lvl, v in (("Warm", w), ("Cold-Drug", cd), ("Cold-Target", ct), ("Cold-Pair", cp))}
for seed in (1, 2, 3):
    pat = rf"\n{seed} \| ([−+-][\d.]+) \| ([−+-][\d.]+)"
    chk(7, "vis", pat, lambda m, seed=seed: (close(num(m[1]), dr[(seed, "Cold-Drug")], 5e-5) and close(num(m[2]), dr[(seed, "Cold-Pair")], 5e-5), f"slide {m[1]}, {m[2]} vs md tables {dr[(seed,'Cold-Drug')]:+.4f}, {dr[(seed,'Cold-Pair')]:+.4f}"), f"DrugBAN raw deltas, seed {seed}")
neg = sum(v < 0 for v in dr.values())
chk(7, "vis", r"(\d+) of its (\d+) seed-level values are negative", lambda m: (int(m[1]) == neg and int(m[2]) == len(dr), f"slide {m[1]} of {m[2]} vs {neg} of {len(dr)} in the md tables"), "DrugBAN: 6 of 12 negative")
chk(7, "vis", r"DrugBAN, DAVIS: two of four levels", lambda m: (len(dr) == 12 and re.search(r"\n1 \| ", S[7]["vis"]) is not None, "header states the table shows two of the four levels (cold-drug, cold-pair); 12 values exist, 6 shown, and the slide says 6 of 12 are negative"), "DrugBAN table scope stated (wording fixed)")
# ---- slide 8
chk(8, "vis", r"(\d+) of (\d+) cells: seeds disagree", lambda m: (int(m[1]) == kn("seeds_disagree_exact") and int(m[2]) == tot, f"slide {m[1]} of {m[2]} vs {kn('seeds_disagree_exact'):.0f} of {tot}"), "checklist 1: seeds disagree")
chk(8, "vis", r"(\d+) of (\d+) DAVIS cells survives Holm \(median p over seeds\)", lambda m: (int(m[1]) == 1 and int(m[2]) == 20 and rx(r"HOLM on my exact median-of-seeds p.*?survivors (\d+) of (\d+)", T4)[1] == "1", "1 of 20 with the aggregation rule stated"), "checklist 4: Holm 1 of 20 (median rule stated)")
chk(8, "vis", r"(\d+) of (\d+) “unseen” proteins seen in training", lambda m: (int(m[1]) == len(leaked) and int(m[2]) == len(tenames), f"{m[1]} of {m[2]} vs {len(leaked)} of {len(tenames)}"), "checklist 8: 12 of 88")
chk(8, "vis", r"Residue chance is only ([\d.]+)–([\d.]+) on DAVIS", lambda m: (all(0.019 <= round(c, 3) <= 0.020 for c in davis_chances) and close(num(m[1]), round(min(davis_chances), 3), 1e-9) and close(num(m[2]), round(max(davis_chances), 3), 1e-9), f"slide {m[1]}–{m[2]} vs exact chance {min(davis_chances):.4f}–{max(davis_chances):.4f} over DAVIS cells"), "checklist 2: residue chance 0.019-0.020")
rc = {r["readout"]: r for r in csv.DictReader(open("results/readout_comparison.csv")) if r["ground truth"] == "klifs" and r["model"] == "hyperattentiondti" and r["level"] == "cold_target"}
lead = lambda cell: num(re.match(r"[\d.]+", cell)[0])
chk(8, "vis", r"Same weights: ([\d.]+) vs ([\d.]+) in the pocket", lambda m: (close(num(m[1]), lead(rc["maxchannel"]["precision@10"]), 5e-4) and close(num(m[2]), lead(rc["receptive"]["precision@10"]), 5e-4), f"slide {m[1]} vs {m[2]}; readout_comparison.csv {rc['maxchannel']['precision@10']} vs {rc['receptive']['precision@10']}"), "checklist 5: 0.367 vs 0.081", "SOURCE-ONLY")
chk(8, "notes", r"chance of ([\d.]+)\. One says ([\d.]+) times chance", lambda m: (close(num(m[1]), lead(rc["maxchannel"]["chance"]), 5e-4) and close(num(m[2]), lead(rc["maxchannel"]["precision@10"]) / lead(rc["maxchannel"]["chance"]), 0.06), f"notes chance {m[1]}, ratio {m[2]} vs {lead(rc['maxchannel']['precision@10'])/lead(rc['maxchannel']['chance']):.2f}"), "notes: 2.6 times chance", "SOURCE-ONLY")
dd = open("results/drug_dependence/moltrans.txt").read()
chk(8, "vis", r"MolTrans readout scored: same top ten for every drug", lambda m: ("100%" in dd and "0%" in open("results/drug_dependence/moltrans_interaction.txt").read(), "readout scored: 100% identical; the interaction-map readout is 0% identical (results/drug_dependence/moltrans_interaction.txt); slide says readout, notes give the qualifier"), "checklist 6: MolTrans same top ten (qualified)")
chk(8, "vis", r"Detects a ([\d.]+) dose at every DAVIS level", lambda m: (close(num(m[1]), 0.02, 1e-9), "results/positive_control_davis.md states 0.02 (repo's own positive control; not recomputed here)"), "checklist 3: 0.02 dose", "SOURCE-ONLY")
# ---- slide 9 (compute)
wb = json.load(open("config/wave_budget.json")); acc = wb["per_account"]
chk(9, "vis", r"ACCOUNT 1 · (\d+) CELLS[\s\S]*?([\d.]+) GPU-hours \(([\d.]+)–([\d.]+)\)", lambda m: (int(m[1]) == acc["ACC1"]["cells"] and close(num(m[2]), acc["ACC1"]["gpu_hours_mean"], 0.05) and close(num(m[3]), acc["ACC1"]["gpu_hours_low"], 0.05) and close(num(m[4]), acc["ACC1"]["gpu_hours_high"], 0.05), f"slide {m[1]} cells, {m[2]} ({m[3]}-{m[4]}) vs config/wave_budget.json {acc['ACC1']['cells']}, {acc['ACC1']['gpu_hours_mean']} ({acc['ACC1']['gpu_hours_low']}-{acc['ACC1']['gpu_hours_high']})"), "account 1 cells and hours", "SOURCE-ONLY")
chk(9, "vis", r"ACCOUNT 2 · (\d+) CELLS[\s\S]*?([\d.]+) GPU-hours", lambda m: (int(m[1]) == acc["ACC2"]["cells"] and close(num(m[2]), acc["ACC2"]["gpu_hours_mean"], 0.05), f"slide {m[1]} cells, {m[2]} vs {acc['ACC2']['cells']}, {acc['ACC2']['gpu_hours_mean']}"), "account 2 cells and hours", "SOURCE-ONLY")
chk(9, "vis", r"ACCOUNT 3 · (\d+) CELLS", lambda m: (int(m[1]) == acc["ACC3"]["cells"] and acc["ACC3"]["unmeasured_cells"] == acc["ACC3"]["cells"], f"slide {m[1]} cells vs {acc['ACC3']['cells']}; unmeasured {acc['ACC3']['unmeasured_cells']}"), "account 3 cells; hours unmeasured", "SOURCE-ONLY")
chk(9, "vis", r"(\d+) training jobs", lambda m: (int(m[1]) == sum(acc[a]["cells"] for a in acc), f"slide {m[1]} vs {sum(acc[a]['cells'] for a in acc)} cells in wave_budget.json"), "30 training jobs", "SOURCE-ONLY")
chk(9, "vis", r"need ([\d.]+) \(mean\) to ([\d.]+) \(high case\)", lambda m: (close(num(m[1]), acc["ACC1"]["gpu_hours_mean"] / 0.85, 0.06) and close(num(m[2]), acc["ACC1"]["gpu_hours_high"] / 0.85, 0.06), f"slide {m[1]}, {m[2]} vs 23.2/0.85 = {acc['ACC1']['gpu_hours_mean']/0.85:.2f}, 24.7/0.85 = {acc['ACC1']['gpu_hours_high']/0.85:.2f}"), "quota needed with a 15% reserve (arithmetic)")
chk(9, "vis", r"Quota: (\d+) GPU-hours per week", lambda m: (True, "quota was stated by the user on 2026-09-25 (docs/wave_plan.md); not verifiable from data"), "quota 30 GPU-h per week", "EXTERNAL")
chk(9, "notes", r"need about (\d+) GPU-hours per account", lambda m: (close(num(m[1]), acc["ACC1"]["gpu_hours_mean"], 0.5), f"notes {m[1]} vs {acc['ACC1']['gpu_hours_mean']} per account"), "notes: about 23 GPU-hours per account")
chk(9, "notes", r"spending about (\d+) GPU-hours", lambda m: (close(num(m[1]), 2 * acc["ACC1"]["gpu_hours_mean"], 0.5), f"notes {m[1]} vs 2 x {acc['ACC1']['gpu_hours_mean']} = {2*acc['ACC1']['gpu_hours_mean']:.1f}"), "notes: about 46 GPU-hours")
# ---- slide 10
d20 = rx(r"HOLM on my exact median-of-seeds p.*?survivors (\d+) of (\d+)", T4); k8 = re.findall(r"HOLM on my exact median-of-seeds p.*?survivors (\d+) of (\d+)", T4)[1]
chk(10, "vis", r"(\d+) of (\d+) DAVIS cells, (\d+) of (\d+) KIBA cells after correction", lambda m: ((int(m[1]), int(m[2]), int(m[3]), int(m[4])) == (int(d20[1]), int(d20[2]), int(k8[0]), int(k8[1])), f"slide {m.groups()} vs recomputed Holm {(d20[1], d20[2], k8[0], k8[1])}"), "Holm survivors DAVIS 1 of 20, KIBA 0 of 8")
chk(10, "vis", r"Seeds disagree in (\d+) of (\d+) cells", lambda m: (int(m[1]) == kn("seeds_disagree_exact") and int(m[2]) == tot, f"slide {m[1]} of {m[2]} vs {kn('seeds_disagree_exact'):.0f} of {tot}"), "seeds disagree")
chk(10, "vis", r"Load-bearing in (\d) of (\d) models; pocket enrichment for (\d)", lambda m: (int(m[1]) == 3 and int(m[2]) == 4 and int(m[3]) == sum(1 for x in (xa, ha) if int(x) > 0), f"slide {m.groups()} vs 3 models with all intervals above zero (of 4) and {sum(1 for x in (xa, ha) if int(x) > 0)} models with pocket survivors"), "load-bearing 3 of 4; pocket enrichment 2")
rho = rx(r"enrichment \(precision@10 / chance\)\s+rho = ([+-][\d.]+)\s+95% percentile bootstrap over cells \[([+-][\d.]+), ([+-][\d.]+)\]", T5c)
chk(10, "vis", rf"ρ = ([\d.]+) \[{MINUS}([\d.]+), ([\d.]+)\] over (\d+) DAVIS cells", lambda m: (close(num(m[1]), num(rho[1]), 0.005) and close(-num(m[2]), num(rho[2]), 0.02) and close(num(m[3]), num(rho[3]), 0.02) and int(m[4]) == 48, f"slide {m[1]} [-{m[2]}, {m[3]}] n={m[4]} vs independent {rho[1]} [{rho[2]}, {rho[3]}] n=48 (enrichment)"), "Spearman rho, accuracy vs localisation")
jt = junit_tests()
chk(10, "vis", r"(\d[\d,]*) passing tests", lambda m: ((None, "junit xml not provided (set JUNIT_XML); count not re-verified") if jt is None else (int(num(m[1])) == jt[0] and jt[1] == "0" and jt[2] == "0", f"slide {m[1]} vs junit passed {jt[0]} (failures {jt[1]}, errors {jt[2]})")), "passing tests")
chk(10, "vis", r"(\d+) numbers in the draft machine-checked against their source files, (\d+) failures", lambda m: (bool(prov_total) and int(m[1]) == int(prov_total[1]) and int(m[2]) == int(prov_total[3]) == 0, f"slide {m[1]} numbers / {m[2]} failures vs checker {prov_total.groups() if prov_total else None}"), "numbers machine-checked, 0 failures")
chk(10, "vis", r"(\d+) trained models", lambda m: (int(m[1]) == n_pred + n_drugban, f"{m[1]} vs {n_pred + n_drugban}"), "84 trained models (conclusion slide)")
chk(10, "vis", r"(\d+) of (\d+) “unseen” proteins seen in training", lambda m: (int(m[1]) == len(leaked) and int(m[2]) == len(tenames), f"slide {m[1]} of {m[2]} vs {len(leaked)} of {len(tenames)} recomputed from the split CSVs"), "conclusion: the DAVIS leak (12 of 88)")
chk(10, "vis", r"The fix: an eight-point checklist", lambda m: (all(re.search(rf"(^|\n){n}\n", S[8]["vis"]) for n in range(1, 9)) and not re.search(r"(^|\n)9\n", S[8]["vis"]), "slide 8 carries checklist items numbered 1 to 8 and no 9th"), "conclusion: the eight-point checklist exists on slide 8")
chk(10, "notes", r"inflates AUROC on those rows by ([\d.]+) \(p = ([\d.]+)\)", lambda m: (close(num(m[1]), kn("leak_ct_leaked_rows"), 5e-4) and close(num(m[2]), kn("leak_ct_leaked_rows", "p"), 5e-5), f"notes {m[1]} (p {m[2]}) vs {kn('leak_ct_leaked_rows'):.4f} (p {kn('leak_ct_leaked_rows','p'):.4f})"), "notes: leaked-row inflation")
chk(10, "notes", r"12 of the 88", lambda m: (len(leaked) == 12 and len(tenames) == 88, f"{len(leaked)} of {len(tenames)}"), "notes: 12 of the 88")

# ------------------------------------------------------------------ 4. traps
print("\n=== NAMING TRAP: code-name 'ColdSite' ===")
name_rx = re.compile(r"cold[\s_-]?site", re.I); bad = 0
for i in S:
    for w in ("vis", "notes", "alt"):
        for m in name_rx.finditer(S[i][w]):
            ctx = S[i][w][max(0, m.start() - 60):m.end() + 40].replace("\n", " ")
            allowed = i == 1 and (("NAMING NOTE" in S[i]["vis"] and w == "vis") or w == "notes")
            print(f"  slide {i} {w:5} {'ALLOWED (naming note)' if allowed else 'FAIL'} ...{ctx}...")
            if not allowed: bad += 1; results.append(("FAIL", i, "code-name on a slide", ctx))
zf = __import__("zipfile").ZipFile(DECK); media_hits = [n for n in zf.namelist() if n.startswith("ppt/slides/") and n.endswith(".xml") and name_rx.search(zf.read(n).decode("utf8", "ignore")) and n != "ppt/slides/slide1.xml"]
print(f"  slide XML parts other than slide 1 containing the code-name: {media_hits or 'none'}")
if media_hits: bad += 1; results.append(("FAIL", 0, "code-name in slide XML", str(media_hits)))
draft = open("paper/v2/INSTRUCTOR_DRAFT.md", encoding="utf-8").read(); prose = re.sub(r"<!--.*?-->", "", draft, flags=re.S)
code_spans = [(m.start(), m.end()) for m in re.finditer(r"`[^`]*`", prose)]
dm = [(prose[max(0, m.start() - 50):m.end() + 40].replace("\n", " "), any(a <= m.start() < b for a, b in code_spans)) for m in name_rx.finditer(prose)]
print(f"  draft prose (comments stripped): {len(dm)} occurrence(s), {sum(not c for _, c in dm)} in running prose, {sum(c for _, c in dm)} inside a `code span` (a file path)")
for c, in_code in dm: print(f"    {'code path' if in_code else 'PROSE    '} ...{c}...")
if sum(not c for _, c in dm) != 1: results.append(("WARN", 0, "draft prose mentions of the code-name", "running prose should contain exactly the one naming sentence"))
for c, in_code in dm:
    if in_code: results.append(("WARN", 0, "draft cites a file path containing the code-name", c))
files = [p for p in glob.glob("results/**/*", recursive=True) if os.path.isfile(p) and p.endswith((".md", ".csv", ".txt", ".json", ".log"))]
hit = {p: len(name_rx.findall(open(p, encoding="utf-8", errors="ignore").read())) for p in files}; hit = {p: n for p, n in hit.items() if n}
print(f"  results/: {len(hit)} of {len(files)} text files contain the name (raw logs, tables and JSON keys); files the slides or draft cite as sources:")
cited = set(re.findall(r"(results/[\w./\-]+?\.(?:md|csv|txt|json))", S[1]["vis"] + "".join(S[i]["vis"] + S[i]["notes"] for i in S) + draft))
for p in sorted(cited & set(hit)): print(f"    WARN cited file exposes the code-name: {p} ({hit[p]}x)"); results.append(("WARN", 0, "cited file exposes the code-name", p))
print("\n=== OVERCLAIM TRAP ===")
over = re.compile(r"\bSOTA\b|state[- ]of[- ]the[- ]art|novel architecture|new (?:model|architecture|method)|outperform\w*|best[- ]in[- ]class|breakthrough|first to\b|unprecedented|revolution\w*|superior to|beats? (?:the )?(?:baseline|published)", re.I)
n_over = 0
for label, text in [(f"slide {i} {w}", S[i][w]) for i in S for w in ("vis", "notes")] + [("draft prose", prose)]:
    for m in over.finditer(text):
        ctx = text[max(0, m.start() - 40):m.end() + 30].replace("\n", " "); neg = bool(re.search(r"(not an?|no|never|instead of|rather than( an?)?|nor)\s+$", text[max(0, m.start() - 20):m.start()], re.I))
        print(f"  {label:14} {'NEGATED (ok)' if neg else 'FLAG':12} ...{ctx}..."); n_over += not neg
        if not neg: results.append(("FAIL", 0, "overclaim vocabulary", ctx))
print(f"  un-negated overclaim hits: {n_over}")
print("\n=== STALE NUMBERS (pre-correction wording) ===")
stale = [r"12 of 22", r"9 of the 12", r"None pass in 9", r"had none pass\. 9", r"0\.019 AUROC on all test rows", r"worth 0\.019", r"826 numbers", r"we have 12", r"Only 1 of 20 DAVIS cells survives Holm(?! \()"]
ns = 0
for i in S:
    for w in ("vis", "notes"):
        for p in stale:
            if re.search(p, S[i][w]): print(f"  FAIL slide {i} {w}: stale text {p!r}"); ns += 1; results.append(("FAIL", i, "stale number", p))
for p in stale[:6] + stale[7:8]:
    if re.search(p, prose): print(f"  FAIL draft prose: stale text {p!r}"); ns += 1; results.append(("FAIL", 0, "stale number in draft", p))
print(f"  stale strings found: {ns}")
print("\n=== COMPUTE TRAP: Wave A framed as planned, and no Wave A results exist ===")
seed45 = [p for p in glob.glob("results/**/*", recursive=True) if re.search(r"seed[_]?[45](?!\d)", os.path.basename(p))]
db_kiba = [p for p in glob.glob("results/**/*", recursive=True) if re.search(r"drugban.*kiba|kiba.*drugban", os.path.basename(p), re.I)]
print(f"  files with seed 4 or 5 in results/: {seed45 or 'none'}; DrugBAN-on-KIBA files: {db_kiba or 'none'}")
if seed45 or db_kiba: results.append(("FAIL", 9, "Wave A artifacts exist", str(seed45 + db_kiba)))
done = re.findall(r"Done: ([^\n]+)", S[9]["vis"]); allowed = {"notebooks built", "dry-run checks pass"}
print(f"  slide 9 'Done:' items: {done}; results claimed as done: {[d for d in done if d not in allowed] or 'none'}")
if [d for d in done if d not in allowed]: results.append(("FAIL", 9, "Wave A results presented as done", str(done)))
for needle in ("planned", "gated", "No Wave A result appears in any number in the paper", "canary must match an old result", "Hours not yet measured"):
    ok = needle in S[9]["vis"]; print(f"  slide 9 says {needle!r}: {ok}")
    if not ok: results.append(("FAIL", 9, "Wave A framing", needle))
also = [w for w in ("Wave A",) if any(w in S[i]["vis"] for i in S if i != 9)]
print(f"  Wave A mentioned outside slide 9 (visible text): {also or 'no'}")

# ------------------------------------------------------------------ 5. accounting
print("\n=== NUMERIC TOKEN ACCOUNTING (visible slide text) ===")
tok = re.compile(r"(?<![\w.])[+−-]?\d[\d,]*(?:\.\d+)?")
unreg = []
for i in S:
    text = S[i]["vis"]; spans = [(a, b) for w, a, b in covered[i] if w == "vis"]
    for m in tok.finditer(text):
        if any(a <= m.start() < b for a, b in spans): continue
        pre = text[max(0, m.start() - 16):m.start()]; t = m.group(0).rstrip(",")
        if re.match(r"\d+ / 10\b", text[m.start():]) or pre.endswith("/ "): continue                      # page numbers "n / 10"
        if re.search(r"(Figure|Fig\.|Box|§|BRIEFING ·|SEPTEMBER|draft §|Table|Image|RESULT|@|BOX|seed\{)\s*$", pre) or re.fullmatch(r"(19|20)\d\d", t): continue   # labels, image indices, years, precision@10
        if re.fullmatch(r"\d(,\d)*", t) and re.search(r"seeds? \d?[{]?$|\{[\d,]*$", pre + t): continue     # 'seeds 1–3', 'seed{1,2,3}'
        if t == "0.05" and pre.rstrip().endswith("="): continue                                             # the conventional alpha, stated as such
        if t == "95" and text[m.end():m.end() + 1] == "%": continue                                         # interval level
        unreg.append((i, t, text[max(0, m.start() - 30):m.end() + 25].replace("\n", " ")))
print(f"  numeric tokens not claimed by any check: {len(unreg)}")
for i, t, c in unreg: print(f"    slide {i:>2} '{t}' ...{c}...")

# ------------------------------------------------------------------ summary
from collections import Counter
cnt = Counter(r[0] for r in results)
print("\n=== SUMMARY ===")
print("  " + "   ".join(f"{k}: {v}" for k, v in sorted(cnt.items())))
for s, sl, c, d in results:
    if s in ("FAIL", "WARN"): print(f"  {s:4} slide {sl}: {c} -- {d[:170]}")
sys.exit(1 if cnt.get("FAIL") else 0)
