"""Concatenate the paper/v2 section files into one manuscript: paper/v2/INSTRUCTOR_DRAFT.md.

Order: title, Abstract, Key Points, 1 Introduction, 2 Methods, 3 Results, 4 Discussion, Figures
(image + caption from figures/CAPTIONS.md), Supplementary Methods. The section files stay the source
of truth; edit them and re-run this script.

What changes on the way in:
  * each file's drafting-note comment (the first HTML comment after its heading) is dropped;
  * section headings are demoted one level so that the title is the only level-1 heading;
  * CAPTIONS.md contributes only its figure captions, each preceded by the PNG it describes.
Source tags (<!-- src: ... -->) and claim comments are kept, so the provenance checker runs on the
master file as it does on the sections.

    python scripts/build_instructor_draft.py           # write the file
    python scripts/build_instructor_draft.py --check   # exit 1 if the file is out of date
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V2 = os.path.join(ROOT, "paper", "v2")
OUT = os.path.join(V2, "INSTRUCTOR_DRAFT.md")
SECTIONS = ["introduction.md", "methods.md", "results.md", "discussion.md"]
SUPPLEMENT = "supplement_methods.md"

CAPTION_RE = re.compile(r"^\*\*Figure (\d+) — `([\w]+)`\. (.*)$")


def read(name: str) -> str:
    with open(os.path.join(V2, name), encoding="utf-8") as fh:
        return fh.read()


def drop_first_comment(md: str) -> str:
    """Remove the drafting note: the first HTML comment that opens a line."""
    return re.sub(r"\n<!--(?!\s*src:).*?-->\n", "\n", md, count=1, flags=re.S)


def demote(md: str) -> str:
    return re.sub(r"^(#+) ", r"#\1 ", md, flags=re.M)


def abstract_parts() -> tuple:
    md = drop_first_comment(read("abstract.md"))
    title, _, body = md.partition("\n")
    assert title.startswith("# "), "abstract.md must open with the title"
    # the Key Points note is also a drafting note
    body = re.sub(r"(## Key Points\n)\n<!--(?!\s*src:).*?-->\n", r"\1", body, count=1, flags=re.S)
    return title, body.strip("\n")


def figures() -> str:
    out = ["## Figures"]
    lines = read(os.path.join("figures", "CAPTIONS.md")).split("\n")
    i = 0
    while i < len(lines):
        m = CAPTION_RE.match(lines[i])
        if not m:
            i += 1
            continue
        num, name, rest = m.groups()
        para = [f"**Figure {num}. {rest}"]
        i += 1
        while i < len(lines) and lines[i].strip() and not lines[i].startswith(("**Figure", "#")):
            para.append(lines[i])
            i += 1
        out.append(f"![Figure {num}](figures/{name}.png)")
        out.append("\n".join(para))
    assert len(out) > 1, "no captions found in figures/CAPTIONS.md"
    return "\n\n".join(out)


def build() -> str:
    title, abstract = abstract_parts()
    parts = [
        title,
        "<!-- Generated by scripts/build_instructor_draft.py from the section files in paper/v2/; "
        "edit those and re-run. Every digit keeps its hidden source tag. -->",
        abstract,
    ]
    for name in SECTIONS:
        parts.append(demote(drop_first_comment(read(name))).strip("\n"))
    parts.append(figures())
    parts.append(demote(drop_first_comment(read(SUPPLEMENT))).strip("\n"))
    return "\n\n".join(parts) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if INSTRUCTOR_DRAFT.md is out of date")
    args = ap.parse_args(argv)
    text = build()
    if args.check:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        print("up to date" if current == text else "OUT OF DATE")
        return 0 if current == text else 1
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
